name: Frontend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/test-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/test-frontend.yml'
  workflow_call:
    outputs:
      build-artifact-name:
        description: "Name of the frontend build artifact"
        value: ${{ jobs.frontend-test.outputs.artifact-name }}

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-id }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Run linter
      run: npm run lint

    - name: Run unit tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Upload build artifacts
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: frontend/dist/
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-test-results-${{ github.sha }}
        path: |
          frontend/coverage/
          frontend/test-results/
        retention-days: 7
